/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/outage-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Outage Reports
         * @description Return all outage reports (newest first).
         */
        get: operations["list_outage_reports_outage_reports_get"];
        put?: never;
        /**
         * Create Outage Report
         * @description Submit a new outage report (without an image).
         *
         *     To attach an image, follow up with POST /outage-reports/{id}/image.
         */
        post: operations["create_outage_report_outage_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outage-reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Outage Report
         * @description Return a single outage report by ID.
         */
        get: operations["get_outage_report_outage_reports__report_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Outage Report
         * @description Delete an outage report and its associated image.
         */
        delete: operations["delete_outage_report_outage_reports__report_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outage-reports/{report_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Image
         * @description Download the raw image attached to an outage report.
         */
        get: operations["download_image_outage_reports__report_id__image_get"];
        put?: never;
        /**
         * Upload Image
         * @description Attach (or replace) an image for an existing outage report.
         *
         *     Accepted content types: JPEG, PNG, WebP, GIF.
         */
        post: operations["upload_image_outage_reports__report_id__image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_image_outage_reports__report_id__image_post */
        Body_upload_image_outage_reports__report_id__image_post: {
            /** File */
            file: string;
        };
        /**
         * EquipmentType
         * @description Types of accessibility equipment that can be reported as broken down.
         * @enum {string}
         */
        EquipmentType: "lift" | "escalator";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * OutageReportCreate
         * @description Payload accepted when submitting a new outage report.
         *
         *     `image` and `image_content_type` are handled separately via a multipart
         *     upload endpoint rather than JSON, so they are absent here.
         */
        OutageReportCreate: {
            equipment_type: components["schemas"]["EquipmentType"];
            station: components["schemas"]["Station"];
            /** Connection */
            connection: string;
            /**
             * Breakdown Time
             * Format: date-time
             */
            breakdown_time: string;
            /** Description */
            description?: string | null;
        };
        /**
         * OutageReportSummary
         * @description Outage report returned by list and single-item endpoints.
         *
         *     Image bytes are intentionally absent — use GET /outage-reports/{id}/image
         *     to retrieve them.  `image_content_type` is kept so callers can tell whether
         *     an image exists without downloading it.
         */
        OutageReportSummary: {
            equipment_type: components["schemas"]["EquipmentType"];
            station: components["schemas"]["Station"];
            /** Connection */
            connection: string;
            /**
             * Breakdown Time
             * Format: date-time
             */
            breakdown_time: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: number;
            /** Image Content Type */
            image_content_type?: string | null;
        };
        /**
         * Station
         * @description Stations where an outage can be reported.
         * @enum {string}
         */
        Station: "Victoria" | "Waterloo" | "Paddington" | "King's Cross" | "London Bridge";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_outage_reports_outage_reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutageReportSummary"][];
                };
            };
        };
    };
    create_outage_report_outage_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutageReportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutageReportSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_outage_report_outage_reports__report_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutageReportSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_outage_report_outage_reports__report_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_image_outage_reports__report_id__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_image_outage_reports__report_id__image_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_outage_reports__report_id__image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutageReportSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
